services:
  - type: web
    name: discord-music-bot
    env: python
    buildCommand: "apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: DISCORD_TOKEN
        sync: false   # tu le renseignes manuellement dans le dashboard Render
